### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by claybiockiller**

### CODE REVIEW

**Comment by 3TUSK** [comment]
Then what's the meaning of localizing JadedTweaks...?

**Comment by claybiockiller** [comment]
3T is everywhere... I'm Preparing to post on MCBBS(The Chinese Minecraft Forum)!
3T无处不在。。。准备将来在MCBBS发帖啊！

**Comment by 3TUSK** [comment]
then please check out #stopmodrepost. Do you really believe that it is an addon for thaumcraft? Have you ever played AS2 or magic farm 3?

**Comment by claybiockiller** [comment]
WHAT? stopmodrepost? MCBBS is not on https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md . And I think every mod supports Thaumcraft can be considered as addon for thaumcraft. I admit i never played AS2 or magic farm 3...
什么？stopmodrepost？MCBBS不在 https://github.com/VictiniX888/Illegal-Mod-Sites/blob/master/SITES.md 上啊。我认为任何支持神秘的模组都是神秘扩展。我承认我没玩过AS2或者magic farm 3。
Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by 3TUSK** [comment]
How many percentages of repost on mcbbs haven't get any permission? Also, Agrimancy has the idea of miracle from farming, which is basically equivalent to the idea of _ex nihilo_ (latin. out of nothing). If you say 地灵术 (lit. Spell of subterranean spirit), I believe that you fail to express the idea correctly. Last, that this mod support thaumcraft doesn't means it's thaumcraft addon. It _is_ aiming to improve compatibility between mods under the circumstances of skyland map. That is what I, as a passing localization volunteer, want to say here.

**Comment by 3TUSK** [comment]
@jadedcat I apologize for my aggressive comment if you feel so, but I don't think you should merge this localization pull request. I believe that he failed to express the context.

**Comment by claybiockiller** [comment]
地灵术 is changed.
地灵术已改。

**Comment by 3TUSK** [comment]
How about 农耕秘法 (lit. The secret magic of farming)? I know it's hard to connect "agri" and "mancy" together in Chinese...

**Comment by claybiockiller** [comment]
Maybe 农之魔力（it also means magic of farming) is also good?
也许农之魔力也不错呢？

**Comment by claybiockiller** [comment]
Maybe 农之魔力（it also means magic of farming) is also good?
也许农之魔力也不错呢？

**Comment by claybiockiller** [comment]
Maybe 农之魔力（it also means magic of farming) is also good?
也许农之魔力也不错呢？

**Comment by 3TUSK** [comment]
Leave here for further discussion.

**Pull request closed without merging**
